/-
Copyright (c) 2026 Benjamin Brast-McKie. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Benjamin Brast-McKie
-/

import FormalSystem.Semantics.Validity
import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.Data.Rat.Cast.Order
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum

/-!
# The periodic clock frame

The independence witness for `CO ⊬ Prior-U` is built on a single frame, defined here: the
**periodic clock**.

* the temporal order is `D = ℚ` — a nontrivial totally ordered abelian group, which is all
  `def:temporal-order` requires of it; nothing in `def:frame` constrains `D` to be gapless;
* the world-state carrier is the *rational circle* `W = ℚ ⧸ ℤ`;
* the task relation is the deterministic translation flow `w ⇒_x u :⟺ u = w + ⟦x⟧`.

## Why the quotient

The torsion in `ℚ ⧸ ℤ` is load bearing, not decorative. Duration `1` is a **looping duration**:
`⟦1⟧ = 0`, so `w ⇒_1 w` and nothing else. `def:world-history`'s task-respect clause then forces
every total history to be `1`-periodic — periodicity is a consequence of the frame, not an extra
assumption — and `Metalogic/Independence/LoopingDuration.lean` turns that into validity of every
`CO` instance. On the *un-quotiented* line frame (`W = ℚ`, `u = w + x`) the same time shift moves
world states rather than fixing them and the argument collapses.

## Pre-empting the "degenerate model" objection

This frame validates `Hψ → Gψ` for every `ψ`, which is not a principle of the intended reading of
the logic. That is expected and harmless: an independence witness is a model of the assumptions,
not a model of the intended interpretation. Three points make the witness legitimate:

* `clockFrame` is a genuine value of the `ℚ` fibre, `FrameOver (TemporalOrder.of ℚ)`. Every one of `def:frame`'s four axioms —
  *Compositionality*, *Seriality*, *Limit*, *Saturation* — is discharged below, together with the
  converse convention and the iff-form zero-duration law the structure additionally carries.
* Because it is a genuine frame over a densely ordered `ℚ`, every base and density axiom holds in
  every model on it, for free, by `soundness_dense`. Nothing has to be checked by hand.
* The only *extra* principle it validates beyond the dense base is `CO` itself, which is exactly
  the assumption the independence result grants.

## Contents

* `ClockState` — the carrier `ℚ ⧸ AddSubgroup.zmultiples (1 : ℚ)`, with the projection `cmk`.
* `clockFrame` — the `FrameOver (TemporalOrder.of ℚ)` above, with all seven obligations discharged.
* `clockHistory` — the reference total history `t ↦ ⟦t⟧`, with `clockHistory_isTotal`.
-/

namespace FormalSystem.Metalogic.Independence

open FormalSystem.Syntax
open FormalSystem.Semantics

/-! ## The rational circle -/

/--
The world-state carrier of the clock frame: the *rational circle* `ℚ ⧸ ℤ`, presented as the
quotient of `ℚ` by the subgroup generated by `1`.

`QuotientAddGroup` is used directly rather than Mathlib's `AddCircle`, which is the same quotient
but drags in the topological instance stack this development has no use for.
-/
abbrev ClockState : Type := ℚ ⧸ AddSubgroup.zmultiples (1 : ℚ)

/-- The projection `ℚ → ℚ ⧸ ℤ`, written `⟦q⟧` in the prose above. -/
def cmk (q : ℚ) : ClockState := QuotientAddGroup.mk q

@[simp] theorem cmk_zero : cmk 0 = 0 := rfl

theorem cmk_add (a b : ℚ) : cmk (a + b) = cmk a + cmk b := rfl

theorem cmk_neg (a : ℚ) : cmk (-a) = -cmk a := rfl

theorem cmk_sub (a b : ℚ) : cmk (a - b) = cmk a - cmk b := rfl

/-- Two rationals have the same image in the circle exactly when they differ by an integer. -/
theorem cmk_eq_cmk_iff (a b : ℚ) : cmk a = cmk b ↔ ∃ n : ℤ, a - b = (n : ℚ) := by
  simp only [cmk, QuotientAddGroup.eq_iff_sub_mem, AddSubgroup.mem_zmultiples_iff]
  constructor
  · rintro ⟨k, hk⟩; exact ⟨k, by simpa using hk.symm⟩
  · rintro ⟨n, hn⟩; exact ⟨n, by simpa using hn.symm⟩

/-- A rational maps to `0` in the circle exactly when it is an integer. -/
theorem cmk_eq_zero_iff (a : ℚ) : cmk a = 0 ↔ ∃ n : ℤ, a = (n : ℚ) := by
  have h := cmk_eq_cmk_iff a 0
  simpa using h

/-- **Duration `1` loops**: the circle has circumference `1`. -/
@[simp] theorem cmk_one : cmk (1 : ℚ) = 0 := (cmk_eq_zero_iff 1).mpr ⟨1, by norm_num⟩

/-- Every element of the circle is the image of a rational. -/
theorem cmk_surjective : Function.Surjective cmk := by
  intro c
  obtain ⟨q, rfl⟩ := QuotientAddGroup.mk_surjective c
  exact ⟨q, rfl⟩

/-! ## The frame -/

/-- The clock frame's task relation, as a bare relation: the deterministic translation flow. -/
def clockRel (w : ClockState) (x : ℚ) (u : ClockState) : Prop := u = w + cmk x

/-- Every fiber of the clock relation is a subsingleton — the flow is deterministic. -/
theorem clockRel_fib_subsingleton (w : ClockState) (x : ℚ) :
    (TaskFrame.Fib clockRel w x).Subsingleton := by
  rintro u (rfl : u = _) u' (rfl : u' = _)
  rfl

/-- *Limit* (`def:frame#Limit`) for the clock relation.

`limit_of_shift` does not apply: there is no `ℚ`-valued position function on the circle, since
the circle is exactly what forgets the integer part. The argument is run directly instead. A
displacement realized by rationals of arbitrarily small absolute value is realized by a *single*
such rational — any two witnesses below `1/2` in absolute value differ by an integer of absolute
value below `1`, hence by `0` — and that rational is therefore below every positive bound. -/
theorem clockRel_limit :
    ∀ w u : ClockState, (∀ x : ℚ, 0 < x → ∃ y, |y| < x ∧ clockRel w y u) → u = w := by
  intro w u h
  -- A single small witness, taken at radius `1/2`.
  obtain ⟨y₀, hy₀, (hu : u = w + cmk y₀)⟩ := h (1 / 2) (by norm_num)
  -- Every witness at a radius below `1/2` is that same rational.
  have key : ∀ x : ℚ, 0 < x → x ≤ 1 / 2 → |y₀| < x := by
    intro x hx hx'
    obtain ⟨y, hy, (hu' : u = w + cmk y)⟩ := h x hx
    have hcmk : cmk y = cmk y₀ := by
      have hww : w + cmk y = w + cmk y₀ := by rw [← hu', ← hu]
      exact add_left_cancel hww
    obtain ⟨n, hn⟩ := (cmk_eq_cmk_iff y y₀).mp hcmk
    obtain ⟨hy1, hy2⟩ := abs_lt.mp hy
    obtain ⟨hz1, hz2⟩ := abs_lt.mp hy₀
    -- The integer separating the two witnesses has absolute value below `1`, hence is `0`.
    have hnlt : (n : ℚ) < 1 := by rw [← hn]; linarith
    have hngt : (-1 : ℚ) < (n : ℚ) := by rw [← hn]; linarith
    have hn0 : n = 0 := by
      have a1 : n < 1 := by exact_mod_cast hnlt
      have a2 : -1 < n := by exact_mod_cast hngt
      omega
    have hyy : y = y₀ := by rw [hn0] at hn; push_cast at hn; linarith
    rwa [hyy] at hy
  -- Hence `|y₀|` is below every positive bound up to `1/2`, so it is `0`.
  have hy₀zero : y₀ = 0 := by
    by_contra hne
    have hpos : 0 < |y₀| := abs_pos.mpr hne
    exact absurd (key |y₀| hpos (le_of_lt hy₀)) (lt_irrefl _)
  rw [hu, hy₀zero, cmk_zero, add_zero]

/-- *Saturation* (`def:frame#Saturation`) for the clock relation: the flow is deterministic, so
every fibre is a subsingleton and Helper D (`TaskFrame.saturation_of_fib_subsingleton`) applies. -/
theorem clockRel_saturation : TaskFrame.Saturation clockRel :=
  TaskFrame.saturation_of_fib_subsingleton clockRel_fib_subsingleton

/--
**The periodic clock frame.**

`D = ℚ`, `W = ℚ ⧸ ℤ`, `w ⇒_x u :⟺ u = w + ⟦x⟧`. All seven `FrameOver` obligations are discharged;
see this module's docstring for why the quotient (rather than the line) is the right carrier.

The temporal order is written `TemporalOrder.of ℚ` rather than a named `ratOrder`: a single
`ratOrder` would have to live in `Semantics/TemporalOrder.lean` to be visible both here and in
`BXCanonical`, and that module cannot state `⟨Rat⟩` without a new tree-wide Mathlib import. The
naming decision is deferred to the phase that deletes the transitional layer.
-/
def clockFrame : FrameOver (TemporalOrder.of ℚ) where
  WorldState := ClockState
  worldNonempty := ⟨0⟩
  TaskRel := clockRel
  nullity_identity := by
    intro w u
    constructor
    · rintro (rfl : u = _); simp [cmk_zero]
    · rintro rfl; show w = w + cmk 0; simp
  comp := TaskFrame.comp_of
    (by
      rintro w v x y _ _ (hv : v = w + cmk (x + y))
      refine ⟨w + cmk x, rfl, ?_⟩
      show v = w + cmk x + cmk y
      rw [hv, cmk_add, add_assoc])
    (by
      rintro w u v x y _ _ (hu : u = w + cmk x) (hv : v = u + cmk y)
      show v = w + cmk (x + y)
      rw [hv, hu, cmk_add, add_assoc])
  converse := by
    intro w d u
    constructor
    · rintro (rfl : u = _)
      show w = w + cmk d + cmk (-d)
      rw [cmk_neg]; abel
    · rintro (hw : w = u + cmk (-d))
      show u = w + cmk d
      rw [hw, cmk_neg]; abel
  serial := fun w x _ =>
    ⟨⟨w + cmk x, rfl⟩, ⟨w - cmk x, by show w = w - cmk x + cmk x; abel⟩⟩
  limit := clockRel_limit
  saturation := clockRel_saturation

@[simp] theorem clockFrame_worldState : clockFrame.WorldState = ClockState := rfl

@[simp] theorem clockFrame_taskRel (w : ClockState) (x : ℚ) (u : ClockState) :
    clockFrame.TaskRel w x u ↔ u = w + cmk x := Iff.rfl

/-- The clock frame inhabits the `ℚ` fibre: the sanity check the plan names. -/
example : Nonempty (FrameOver (TemporalOrder.of ℚ)) := ⟨clockFrame⟩

/-! ## The reference history -/

/--
The reference history of the clock frame: time `t` sits at circle position `⟦t⟧`.

This is the history the `Prior-U` refutation is stated at. It is total, and `respects_task` holds
by the group law alone: `⟦t⟧ = ⟦s⟧ + ⟦t - s⟧`.
-/
def clockHistory : ConvexHistory clockFrame where
  domain := fun _ => True
  nonempty_domain := ⟨0, trivial⟩
  states := fun t _ => cmk t
  respects_task := by
    intro s t _ _
    show cmk t = cmk s + cmk (t - s)
    rw [← cmk_add]
    congr 1
    ring
  convex := by intro _ _ _ _ _ _ _; trivial

@[simp] theorem clockHistory_states (t : ℚ) (ht : clockHistory.domain t) :
    clockHistory.states t ht = cmk t := rfl

/-- The reference history is total: its domain is all of `ℚ`. -/
theorem clockHistory_isTotal : clockHistory.IsTotal := fun _ => trivial

end FormalSystem.Metalogic.Independence
