/-
Copyright (c) 2026 Benjamin Brast-McKie. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Benjamin Brast-McKie
-/

import Mathlib.Order.Filter.Ultrafilter.Basic
import FormalSystem.Init

/-!
# The index ultrafilter

The ultraproduct that builds a model for a finitely satisfiable set `Γ` is indexed by the finite
sublists of `Γ`. This module supplies that index type and the ultrafilter on it:

* `Idx Γ` — the subtype of lists all of whose members lie in `Γ`;
* `tailFilter Γ` — the filter generated by the up-sets of sublist inclusion, built directly from
  its three filter fields;
* `idxUF Γ` — `Ultrafilter.of (tailFilter Γ)`, which exists because `tailFilter Γ` is `NeBot`;
* `eventually_mem` — **the key property**: every `ψ ∈ Γ` is eventually in the index list, which is
  what makes each `ψ ∈ Γ` eventually true at the per-index witness, hence true in the
  ultraproduct.

Everything is stated generically over `α : Type u`; the consumer instantiates
`α := FormalSystem.Syntax.Formula`. The generic form is deliberate — there is nothing
formula-specific in the construction, and specializing it would only add an import.

## Why not `Filter.atTop`

`Filter.atTop_neBot` requires a registered `Preorder` **instance** on `Idx Γ` plus
`IsDirectedOrder` and `Nonempty` — a global instance-graph commitment on a `List` subtype, made
for a single use. The hand-built `tailFilter` is both shorter (its three fields are sixteen
lines) and instance-free, so `Mathlib.Order.Filter.AtTopBot.*` is deliberately not imported.

## What is deliberately not here

The carrier construction (`Ultraproduct/Carrier.lean`), the ultraproduct shift set
(`Ultraproduct/ShiftSetProduct.lean`), and the Łoś lemma (`Ultraproduct/Los.lean`). This module
depends on none of them and they depend on nothing here except `idxUF` and `eventually_mem`.

## Axiom profile

`eventually_mem` reports `[propext, Classical.choice, Quot.sound]`; `Classical.choice` enters
solely through `Ultrafilter.of`.
-/

open Filter

namespace FormalSystem.Semantics.Ultraproduct

universe u
variable {α : Type u}

/-- Index type: the finite sublists of `Γ`. -/
abbrev Idx (Γ : Set α) := {L : List α // ∀ ψ ∈ L, ψ ∈ Γ}

/-- The "tail" filter on the index type: generated by the up-sets of sublist inclusion. -/
def tailFilter (Γ : Set α) : Filter (Idx Γ) where
  sets := {s | ∃ L : Idx Γ, {L' : Idx Γ | ∀ ψ ∈ L.val, ψ ∈ L'.val} ⊆ s}
  univ_sets := ⟨⟨[], by simp⟩, fun _ _ => trivial⟩
  sets_of_superset := by
    rintro s t ⟨L, hL⟩ hst
    exact ⟨L, hL.trans hst⟩
  inter_sets := by
    rintro s t ⟨L1, h1⟩ ⟨L2, h2⟩
    refine ⟨⟨L1.val ++ L2.val, ?_⟩, ?_⟩
    · intro ψ hψ
      rcases List.mem_append.mp hψ with h | h
      · exact L1.property ψ h
      · exact L2.property ψ h
    · intro L' hL'
      simp only [Set.mem_setOf_eq, List.mem_append] at hL'
      exact ⟨h1 (fun ψ hψ => hL' ψ (Or.inl hψ)), h2 (fun ψ hψ => hL' ψ (Or.inr hψ))⟩

theorem mem_tailFilter {Γ : Set α} {s : Set (Idx Γ)} :
    s ∈ tailFilter Γ ↔ ∃ L : Idx Γ, {L' : Idx Γ | ∀ ψ ∈ L.val, ψ ∈ L'.val} ⊆ s := Iff.rfl

instance tailFilter_neBot (Γ : Set α) : (tailFilter Γ).NeBot := by
  constructor
  intro h
  have hmem : (∅ : Set (Idx Γ)) ∈ tailFilter Γ := by rw [h]; exact Filter.mem_bot
  obtain ⟨L, hL⟩ := mem_tailFilter.mp hmem
  exact hL (fun _ h => h)

/-- The ultrafilter on the index type. -/
noncomputable def idxUF (Γ : Set α) : Ultrafilter (Idx Γ) := Ultrafilter.of (tailFilter Γ)

/-- **The key property**: every member of `Γ` is eventually in the index list. This is what
makes each `ψ ∈ Γ` eventually true at the per-index witness, hence true in the ultraproduct. -/
theorem eventually_mem (Γ : Set α) {ψ : α} (hψ : ψ ∈ Γ) :
    ∀ᶠ L in (idxUF Γ : Filter (Idx Γ)), ψ ∈ L.val := by
  refine Ultrafilter.of_le (tailFilter Γ) ?_
  refine mem_tailFilter.mpr ⟨⟨[ψ], by simpa using hψ⟩, ?_⟩
  intro L' hL'
  exact hL' ψ (by simp)

end FormalSystem.Semantics.Ultraproduct
