// ============================================================================
// p2-frame-classes.typ
// Part I chapter -- Frame Classes and Extensions
// Lean name ground truth: ProofSystem/Axioms.lean, Semantics/FrameClassValidity.lean,
// Semantics/FrameProperty.lean, Semantics/Validity.lean, Syntax/Atom.lean (see ../SYNC-MAP.md).
// ============================================================================

#import "../template.typ": *
#import "../generated/status.typ": base-count, dense-only-count, ztime-only-count, rtime-only-count
#import "@preview/cetz:0.3.4"

= Frame Classes and Extensions

#chapter-header(
  description: [How the base proof system of @sec:formulas and the proof theory chapter extends to dense, discrete, and complete linear orders, how the Since/Until-primitive language relates to the derived Next/Previous operators, and where the deferred tense-primitive subsystem sits relative to the full system.],
  dependencies: [Chapters 1--3 (syntax, semantics, proof theory).],
)


== The `FrameClass` Partial Order

The `FrameClass` classification that parameterizes `DerivationTree` (@sec:formulas) is a *four*-element inductive type with an explicit partial order, defined in `ProofSystem/Axioms.lean`:

#leansrc("FormalSystem.ProofSystem", "FrameClass")
```
inductive FrameClass where
  | Base
  | Dense
  | ZTime
  | RTime
```

`Base` is the bottom element (`FrameClass.base_le`); `Dense` and `ZTime` are incomparable extensions of `Base` -- density and discreteness are jointly inconsistent frame properties, so no derivation may combine both.
`RTime` sits *strictly above* `Dense`, not as a fourth incomparable leaf: it is `ZTime` that is incomparable to both `Dense` and `RTime`.

#align(center)[
  #cetz.canvas({
    import cetz.draw: *

    let nodeBase = (0, 0)
    let nodeDense = (-1.3, 1.6)
    let nodeDiscrete = (1.3, 1.6)
    let nodeDedekind = (-1.3, 3.2)

    // Edges (Hasse diagram: draw before nodes so nodes sit on top)
    line(nodeBase, nodeDense, stroke: (paint: gray.darken(20%), thickness: 1pt))
    line(nodeBase, nodeDiscrete, stroke: (paint: gray.darken(20%), thickness: 1pt))
    line(nodeDense, nodeDedekind, stroke: (paint: gray.darken(20%), thickness: 1pt))

    let node(pos, label) = {
      circle(pos, radius: 0.55, fill: white, stroke: (paint: blue.darken(20%), thickness: 1.2pt))
      content(pos, text(size: 9pt, weight: "bold")[#label])
    }

    node(nodeBase, [Base])
    node(nodeDense, [Dense])
    node(nodeDiscrete, [ZTime])
    node(nodeDedekind, [RTime])
  })
]

#align(center)[
  #text(size: 0.85em, style: "italic")[
    The `FrameClass` lattice, reading upward from `Base`. `Dense` and `ZTime` are incomparable; `RTime` sits *strictly above* `Dense` alone, not as a fourth incomparable leaf, since Reynolds' real-flow axiomatization already contains the density axioms. Per-class axiom assignments are in the table below.
  ]
]

`RTime` extends `Dense` with Reynolds' definable-gap axioms (Prior-U, Prior-S, Sep) because Reynolds' own real-flow axiomatization already contains the density axiom and `dense_indicator` -- making `RTime` a fresh incomparable leaf would make those two axioms inadmissible at `RTime` and so could not host Reynolds' system at all.
This is a primary-source placement, not a design preference: `ProofSystem/Axioms.lean`'s own doc comment traces it to Reynolds 1992 (p.168) axiom by axiom.

Every axiom constructor carries a minimum frame class via `Axiom.minFrameClass` (`ProofSystem/Axioms.lean`), and `DerivationTree`'s axiom rule enforces `ax.minFrameClass ≤ fc`:

#figure(
  table(
    columns: 2,
    stroke: none,
    align: (left, left),
    table.hline(),
    table.header([*Frame class*], [*Axioms assigned*]),
    table.hline(),
    [`Base`], [#base-count axioms (layers 1--5): all base propositional, modal, BX temporal, interaction, and uniformity axioms],
    [`Dense`], [#dense-only-count axioms: `density`, `dense_indicator`],
    [`ZTime`], [#ztime-only-count axioms: `prior_UZ`, `prior_SZ`, `z1`],
    // LEAN-ANCHOR-MAY-MOVE: co-reynolds-independence -- see typst/README.md
    [`RTime`], [#rtime-only-count axioms (Reynolds' definable-gap layer, admissible together with `Dense`'s axioms): `prior_U_gap`, `prior_S_gap`, `sep`],
    table.hline(),
  ),
  caption: [`Axiom.minFrameClass` breakdown (`ProofSystem/Axioms.lean` doc comment; counts regenerated by `scripts/typst-status-counts.sh`).],
)

== Interpreting the Frame-Class Tags Semantically

The syntactic `FrameClass` inductive and its order live entirely inside `ProofSystem/Axioms.lean`, above.
What each tag *denotes* is recorded exactly once, in `Semantics/FrameClassValidity.lean`, by `FrameClass.Sat`, which sends a class tag to the frame condition that class constrains its models by:

- `Base` maps to `True` -- no constraint beyond what every `TaskFrame` already satisfies.
- `Dense` maps to `TaskFrame.IsDense`, i.e. `DenselyOrdered` on the frame's duration group.
- `ZTime` maps to `TaskFrame.IsZTime` -- successor and predecessor structure *together with* successor-Archimedeanness, which is strictly stronger than the bare `TaskFrame.IsDiscrete` clause.
- `RTime` maps to `TaskFrame.IsRTime`, the conjunction of `TaskFrame.IsDense` and `TaskFrame.IsComplete`.

These four frame properties are defined in `Semantics/FrameProperty.lean`; note the naming deviation recorded there, that the paper's Complete clause is this tree's `IsRTime`.

`Semantics/Validity.lean` then builds class-relative validity directly on that interpretation: `ValidIn` at a tag quantifies over exactly the frames `FrameClass.Sat` admits, and the concrete predicates `ValidDense`, `ValidZTime`, and `ValidRTime` are abbreviations for `ValidIn` at `Dense`, `ZTime`, and `RTime` respectively.
Because `FrameClass.Sat` is antitone in the `FrameClass` order (`FrameClass.Sat.anti`), climbing the order shrinks the admitted frame collection, and semantic monotonicity (`ValidIn.mono`) follows as a corollary rather than as a separate argument -- which is what makes it point in the same direction as `DerivationTree.lift`.

== Duration Groups and the Four Classes

The frame classes are best understood through the duration groups that realize them.
Every duration type must be a nontrivial linearly ordered abelian group -- exactly the four instances bundled by `TemporalOrder` (`Semantics/TemporalOrder.lean`) -- which is what validates the seriality axioms BX1/BX1$'$: every time has a strictly later and a strictly earlier time.
No separate seriality hypothesis is carried, because `NoMaxOrder` and `NoMinOrder` already follow from that bundle by instance search.
Within that envelope, the extensions pick out incompatible order structures:

#figure(
  table(
    columns: 3,
    stroke: none,
    align: (left, left, left),
    table.hline(),
    table.header([*Duration group*], [*Class*], [*Why*]),
    table.hline(),
    [$ZZ$], [`ZTime`], [Every element has an immediate successor and predecessor, and iterated succession reaches every later element],
    [$QQ$], [`Dense`], [Strictly between any two elements lies a third; not Dedekind-complete],
    [$RR$], [`RTime`], [Dense, plus every bounded set has a supremum -- the Reynolds definable-gap axioms hold here and nowhere else],
    [$ZZ times ZZ$ (lexicographic)], [`Base` only], [Not dense (nothing lies between $(0,0)$ and $(0,1)$), yet succession from $(0,0)$ never reaches $(1,0)$],
    table.hline(),
  ),
  caption: [Representative duration groups for each frame class.],
)

By `Semantics.complete_duration_discrete_or_dense`, a Dedekind-complete duration group is, up to order-and-group isomorphism, either $ZZ$ or densely ordered; once the density binder is imposed on top of completeness, `RR` is the *only* model up to isomorphism.
`FrameClass.RTime` hosts the complete extension *TM*#sub[c] --- the dense-and-complete (real-flow) system axiomatized by Reynolds' definable-gap triple --- see the correspondence section below for the one order class the system deliberately does not target.

The lexicographic product is the instructive case: it shows that `Base` is not merely the union of the two extensions.
A base-class derivation is sound over *every* admissible duration group, including orders that are neither dense nor discrete, which is why the base axioms must avoid both the density schema and the Prior/Z1 layer.

*Density and discreteness exclude each other.*
The object-language witness is the discreteness indicator $bot #untl top$ ("there is an immediate successor": the guard interval to the witness is empty).
On a discrete order every point has an immediate successor, so $bot #untl top$ holds everywhere; on a dense order the open interval between any point and any strictly later point is nonempty, so the guard $bot$ can never hold throughout it and $bot #untl top$ fails everywhere.
A derivation combining the DI axiom $not (bot #untl top)$ with the Prior/Z1 layer would therefore be sound over no frame at all, and the partial order on `FrameClass` -- with `Dense` and `ZTime` incomparable -- makes such a combination unformulable rather than merely unsound.

*Worked validity: the density schema.*
DN ($G G phi.alt arrow.r G phi.alt$) is valid over dense orders by a two-step argument.
Suppose $G G phi.alt$ holds at time $x$ and let $y > x$ be arbitrary; density supplies $z$ with $x < z < y$; from $G G phi.alt$ at $x$ we get $G phi.alt$ at $z$, and since $y > z$ this gives $phi.alt$ at $y$.
Over $ZZ$ the argument breaks exactly at the appeal to density -- there is no $z$ strictly between $x$ and its immediate successor -- and indeed DN fails there: take $phi.alt$ true everywhere except at $x + 1$.
Then $G phi.alt$ fails at $x$; but for every $y > x$, any $w > y$ satisfies $w gt.eq x + 2$, so $G phi.alt$ holds at every $y > x$ and $G G phi.alt$ holds at $x$.

*Worked validity: the discrete layer.*
Prior-UZ ($F phi.alt arrow.r (not phi.alt #untl phi.alt)$) says that if $phi.alt$ holds somewhere in the future, it holds at a *nearest* future point -- between now and that first witness, $phi.alt$ everywhere fails.
Over $ZZ$ this is the least-number principle applied to the set of future $phi.alt$-times; over $QQ$ it fails, since ${ y : y > x, phi.alt "at" y }$ may have no least element (take $phi.alt$ to hold exactly on the open interval $(x, x+1)$).
Z1 ($G(G phi.alt arrow.r phi.alt) arrow.r (F G phi.alt arrow.r G phi.alt)$) is the backward-induction principle of successor-Archimedean orders @doets1987: if $phi.alt$ is inductive along the strict future order and holds from some future point onward, discreteness lets the property propagate backward step by step to every future time.
Both principles are axioms of frame class `ZTime` and are unavailable at `Base`, matching their failure over dense groups.

*Monotonicity.*
Because `Base` sits below every extension, every base-class theorem is automatically a theorem of all three extended systems: `DerivationTree.lift` coerces derivations upward along the `FrameClass` order, and `ValidIn.mono` confirms semantically that nothing is lost in the coercion.
The general derivation-level soundness theorems of @sec:metalogic (`soundness`, `soundness_dense`, `soundness_ztime`, `soundness_rtime`, `Metalogic/Soundness.lean`) cover all four classes including `RTime`.

== The Frame Properties: Discreteness, Density, and Completeness

// CONFIRM(paper): app:discrete, app:dense, and app:complete prove the frame-property correspondence results
//   this section summarizes.
The Discreteness and Density frame properties are `TaskFrame.IsZTime` and `TaskFrame.IsDense` (`Semantics/FrameProperty.lean`) -- the frame conditions the `ZTime` and `Dense` tags denote, per the interpretation above -- and are carried proof-theoretically by the `ZTime`/`Dense` `FrameClass` axiom layers.
Completeness is carried by `FrameClass.RTime`, which targets the dense-and-complete extension *TM*#sub[c] (real flow) via Reynolds' definable-gap axioms.
One order class lies outside the system's scope *by design*: the bare complete-order class --- completeness alone, with no density binder, whose models are $ZZ$ and $RR$ up to isomorphism, i.e. $op("Th")(ZZ) inter op("Th")(RR)$.
No `FrameClass` constructor targets that intersection: the complete-but-discrete branch is exactly $ZZ$ (covered by `ZTime`/`ValidZTime`) and the complete-dense branch is exactly $RR$ (covered by `RTime`/`ValidRTime`), but the intersection is not itself one frame class, and targeting it would require an axiom set for $op("Th")(ZZ) inter op("Th")(RR)$ that the system does not include.
The book's system does not target that class; its two completeness carriers are the $ZZ$- and $RR$-flow classes separately.

== Next and Previous as Derived Operators

The *Next* and *Previous* operators are derived, not primitive: they are the unsatisfiable-guard instances of the two temporal primitives (@sec:formulas),
$ "Prev" phi.alt := bot #snce phi.alt, quad quad "Next" phi.alt := bot #untl phi.alt. $
$"Next" phi.alt$ at $t$ means $phi.alt$ holds at the immediate successor of $t$ --- the guard $bot$ is vacuously true at no strictly-intermediate time, forcing the witness to be an immediate neighbor --- and dually for $"Prev"$.
// CONFIRM(lean): the next/prev defs in Syntax/Formula.lean take the bot guard in guard-first argument position,
//   with @[simp] unfold lemmas (next_unfold, prev_unfold in Automation/Normalization.lean) characterizing the
//   immediate-successor/predecessor reading over discrete frames.
The characterization is definitional: the unfold lemmas `next_unfold` and `prev_unfold` (`Automation/Normalization.lean`) are `@[simp]`-tagged and proven by `rfl`.

== Deferred: The Tense-Primitive Subsystem <sec:conservative-extension>

The tense-primitive sublanguage --- one-place $H$/$G$ primitive, no Since or Until --- embeds into the book's full language *unconditionally*: the derived-operator definitions of @sec:formulas send every tense-primitive formula to a formula of the full language with the same truth conditions.
// CONFIRM(paper): thm:BLplus-PastFuture states the unconditional language embedding this note asserts.
The subsystem axiomatized over that sublanguage (the twelve-schema presentation recorded in @sec:paper-contrast and the back matter's axiom map) is *deferred*: developing it, and establishing a proof-system conservativity theorem relating it to the full system, is that subsystem's own future result rather than part of this book's system.
// CONFIRM(paper): a conservative-extension theorem for the tense-primitive subsystem is stated (successor of the
//   deleted thm:ConservativeExtension).

One neighboring design fact belongs here: the fresh-atom resource the irreflexivity argument of @sec:design-choices needs is the primitive fact that a fresh atom exists outside any finite set (`Atom.exists_fresh`, `Syntax/Atom.lean`) --- an atom-set fact, independent of the operator-set relationship between the subsystem and the full system.
